export type RestTx = {
  poolId: string;
  poolFee: number;
  positionId: number;
  token0LedgerId: string;
  token0Price: string;
  token0Name: string;
  token0Symbol: string;
  token1LedgerId: string;
  token1Price: string;
  token1Name: string;
  token1Symbol: string;
  actionType: string;
  fromPrincipalId: string;
  fromSubaccount: string;
  fromAccountId: string;
  fromTextualId: string;
  fromAlias: string | null;
  toPrincipalId: string;
  toSubaccount: string;
  toAccountId: string;
  toTextualId: string;
  toAlias: string | null;
  token0AmountIn: string;
  token1AmountIn: string;
  token0AmountOut: string;
  token1AmountOut: string;
  token0Fee: string;
  token1Fee: string;
  sqrtPrice: string;
  tickLimit: string;
  tick: string;
  liquidity: string;
  currentLiquidity: string;
  txHash: string;
  txTime: number;
  token0TxValue: string;
  token1TxValue: string;
};

export type RestFindData = { totalElements: number; content: RestTx[]; page: number; limit: number };
export type RestResponse = { code: number; message: string | null; data: RestFindData };
